### ISSUE TITLE
Slopes aren't correctly lit when oriented

### ISSUE THREAD

**Issue by xerox123official** [BlockySurvival/BlS-issue-tracker#99]
![image](https://user-images.githubusercontent.com/15839662/61173495-0cc8c700-a58c-11e9-90ae-5b2faf486feb.png)

EDIT: Possibly relevant info: Version: Minetest 5.1.0-dev-a687efa6 (Linux)

**Comment by fluxionary** [comment]
PR accepted, just waiting for reboot now.

**Comment by fluxionary** [comment]
Looks good
